# Chapter 3 exercise solution

In [1]:
import math as m

In [2]:
import numpy as np

1. Recall that the hyperbolic sine, denoted by sinh, is $\sinh(x) = \frac{e^x - e^{-x}}{2}$ . Write a function my_sinh(x)
where the output y is the hyperbolic sine computed on x. Assume that x is a 1 by 1 float.

In [3]:
def my_sinh(x):
    result = (m.exp(x)-m.exp(-x))/2
    return result

In [4]:
print(my_sinh(0))

0.0


In [5]:
print(my_sinh(1))

1.1752011936438014


2. Write a function my_checker_board(n) where the output m is an n × n array with the following
form: $$
\begin{bmatrix}
1 & 0 & 1 & 0 & 1 \\
0 & 1 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 & 1 \\
0 & 1 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 & 1 \\
\end{bmatrix}
$$


In [10]:
def my_checker_board(n):
    x = np.zeros((n,n))
    for i in range (0, n):
        for j in range(0, n):
            if (i+j)%2==0:
                x[i,j]=1
    return x

In [11]:
print(my_checker_board(4))

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


3. Write a function my_triangle(b,h) where the output is the area of a triangle with base, b, and
height, h. Recall that the area of a triangle is one-half the base times the height. Assume that b and
h are just 1 by 1 float numbers

In [12]:
def my_trinagle(b,h):
    result = 0.5*b*h
    return result

In [13]:
print(my_trinagle(5,6))

15.0


4. Write a function my_split_matrix(m), where m is an array, the output is a list [m1, m2] where m1 is
the left half of m, and m2 is the right half of m. In the case where there is an odd number of columns,
the middle column should go to m1. Assume that m has at least two columns.

In [35]:
def my_split_matrix(m):
    n = m.shape[1]
    m1 = m[:,:(n//2 + 1)]
    m2 = m[:,(n//2 +1):]
    return [m1,m2]

In [36]:
x = np.array([[1,2,3,4,3],[2,9,4,2,3],[4,5,3,8,5]])
l = my_split_matrix(x)
for i in l:
    print(i)

[[1 2 3]
 [2 9 4]
 [4 5 3]]
[[4 3]
 [2 3]
 [8 5]]


5. Write a function my_cylinder(r,h), where r and h are the radius and height of a cylinder, respectively, and the output is a list [s, v] where s and v are the surface area and volume of the same
cylinder, respectively. Recall that the surface area of a cylinder is 2πr^2 + 2πrh, and the volume is
πr^2h. Assume that r and h are 1 by 1 floats.

In [41]:
import math as m
def my_cylinder(r,h):
    s = 2*m.pi*(r**2) + 2*m.pi*r*h
    v = m.pi*(r**2)*h
    return [s,v]

In [43]:
k = my_cylinder(5,6)
print(f"surface area = {k[0]}")
print(f"volume = {k[1]}")

surface area = 345.5751918948772
volume = 471.23889803846896


6. Write a function my_n_odds(a), where a is a one-dimensional array of floats and the output is the
number of odd numbers in a.

In [44]:
def my_n_odds(a):
    x = a[a%2==1]
    return x.size

In [45]:
print(my_n_odds(np.array([1,5,7,8,9,2,4,5,8])))

5


7. Write a function my_twos(m,n) where the output is an m × n array of twos. Assume that m and n
are strictly positive integers.

In [46]:
def my_twos(m,n):
    x = np.ones((m,n))
    return x+1

In [47]:
print(my_twos(3,2))

[[2. 2.]
 [2. 2.]
 [2. 2.]]


8. Write a lambda function that takes in input x and y, and the output is the value of x-y.

In [48]:
z = lambda x,y : x - y 
print(z(4,1))

3


9. Write a function add_string(s1, s2) where the output is the concatenation of the strings s1 and
s2.

In [49]:
def add_string(s1,s2):
    return s1+s2
print(add_string("hello","world"))

helloworld


10. Generate the following errors:
• TypeError: fun() missing 1 required positional argument: "a"
• IndentationError: expected an indented block

In [52]:
def func(a,b):
    return a+b
print(func(2))

TypeError: func() missing 1 required positional argument: 'b'

In [53]:
def f(a,b):
return a+b

IndentationError: expected an indented block after function definition on line 1 (567231385.py, line 2)

11. Write a function greeting(name, age) where name is a string, age is a float, and the output is a
string "Hi, my name is XXX and I am XXX years old." where XXX are the input name and age,
respectively.

In [54]:
def greeting(name,age):
    s = f"Hi, my name is {name} and i am {age} years old"
    return s

print(greeting("Anika",18))

Hi, my name is Anika and i am 18 years old


12. Let r1 and r2 be the radius of circles with the same center and let r2 > r1. Write a function
my_donut_area(r1, r2) where the output is the area outside of the circle with radius r1 and
inside the circle with radius r2. Make sure that the function is vectorized. Assume that r1 and r2
are one-dimensional arrays of the same size.

In [55]:
def my_donut_area(r1,r2):
    return np.pi * (r2**2 - r1**2)

In [56]:
r1 = np.arange(1, 4)
r2 = np.arange(2, 7, 2)
result = my_donut_area(r1, r2)
print(result)

[ 9.42477796 37.69911184 84.82300165]


13. Write a function my_within_tolerance(A, a, tol) where the output is an array or list of the
indices in A such that |A − a| < tol. Assume that A is a one-dimensional float list or array, and that
a and tol are 1 by 1 floats.

In [57]:
def my_within_tolerance(A,a,tol):
    result = []
    for i in range(len(A)):
        if abs(A[i]-a)<tol:
            result+=[i]
    return result

In [58]:
my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)

[1, 2]

In [59]:
my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)

[47, 48, 49, 50, 51, 52]

14. Write a function bounding_array(A, top, bottom) where the output is equal to the array A wherever bottom < A < top, the output is equal to bottom wherever A <= bottom, and the output is
equal to top wherever A >= top. Assume that A is a one-dimensional float array and that top and
bottom are 1 by 1 floats.

In [60]:
def bounding_array(A, top, bottom):
    return np.clip(A, bottom, top)


In [61]:
bounding_array(np.arange(-5, 6, 1), 3, -3)

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])