# Chapter 5 exercise solutions

1. What will the value of y be after the following code is executed?

In [6]:
y = 0
for i in range(1000):
    for j in range(1000):
        if i == j:
            y += 1

In [7]:
print(y)

1000


2. Write a function my_max(x) to return the maximum (largest) value in x. Do not use the built-in
Python function max.

In [8]:
def my_max(x):
    ans = x[0]
    for i in x:
        if ans < i:
            ans = i
    return ans

In [9]:
print(my_max([1,4,2,3,7,5,3,4,1,9,7]))

9


3. Write a function my_n_max(x, n) to return a list consisting of the n largest elements of x. You may
use Python’s max function. You may also assume that x is a one-dimensional list with no duplicate
entries, and that n is a strictly positive integer smaller than the length of x

In [10]:
def my_n_max(x,n):
    l=[]
    for i in range(n):
        m = max(x)
        l.append(m)
        x.remove(m)
    return l

In [11]:
print(my_n_max([1,4,2,3,6,5,7,4,9],5))

[9, 7, 6, 5, 4]


4. Let m be a matrix of positive integers. Write a function my_trig_odd_even(m) to return an array q,
where q[i, j] = sin(m[i, j]) if m[i, j] is even, and q[i, j] = cos(m[i, j]) if m[i, j] is
odd.

In [3]:
import numpy as np

In [4]:
def my_trig_odd_even(m):
    shape = m.shape
    q = np.zeros(shape)
    for i in range(shape[0]):
        for j in range(shape[1]):
            if m[i,j]%2==0:
                q[i,j] = np.sin(m[i,j])
            else:
                q[i,j] = np.cos(m[i,j])
    return q

In [5]:
print(my_trig_odd_even(np.array([[1,2,3,4],[0,3,2,5]])))

[[ 0.54030231  0.90929743 -0.9899925  -0.7568025 ]
 [ 0.         -0.9899925   0.90929743  0.28366219]]


5. Let P be an m × p array and Q be a p × n array. As you will find later in this book, M = P ×
Q is defined as $M[i, j] = \sum_{k=1}^p P[i, k] \cdot Q[k, j]$
. Write a function my_mat_mult(P, Q) that uses
for-loops to compute M, the matrix product of P * Q. Hint: You may need up to three nested
for-loops. Do not use the function np.dot

In [12]:
def my_mat_mult(P, Q):
    m = len(P)
    p = len(P[0])
    n = len(Q[0])

    M = np.zeros((m,n))

    for i in range(m):
        for j in range(n):
            for k in range(p):
                M[i][j] += P[i][k] * Q[k][j]

    return M   

In [13]:
x = np.array([[2,3],[4,5],[6,3]])
y = np.array([[2,3,4],[4,2,3]])
print(my_mat_mult(x,y))

[[16. 12. 17.]
 [28. 22. 31.]
 [24. 24. 33.]]


6. The interest i on a principle, P0, is a payment for allowing the bank to use your money. Compound
interest is accumulated according to the formula Pn = (1 + i)Pn−1, where n is the compounding
period, usually in months or years. Write a function my_saving_plan(P0, i, goal) where the
output is the number of years it will take P0 to become goal at i% interest compounded annually.

In [17]:
def my_saving_plan(P0,i,goal):
    n = 0
    while P0 < goal:
        P0 = (1+i)*P0
        n += 1
    return n

In [18]:
my_saving_plan(1000, 0.05, 2000)

15

In [19]:
my_saving_plan(500, 0.07, 2000)

21

7. Write a function with my_find(M) where the output is a list of indices i and where M[i] is 1. You
may assume that M is a list of only ones and zeros. Do not use the built-in Python function find.

In [21]:
def my_find(M):
    l = []
    for i in range(len(M)):
        if M[i]==1:
            l += [i]
    return l

In [22]:
my_find([1,0,1,1,0,0,0,1,1,0,1,0,1])

[0, 2, 3, 7, 8, 10, 12]

8. Assume you are rolling two six-sided dice, with each side having an equal chance of occurring.
Write a function my_monopoly_dice() where the output is the sum of the values of the two dice
thrown but with the following extra rule: if the two dice rolls are the same, then another roll is
made, and the new sum added to the running total. For example, if the two dice show 3 and 4, then
the running total should be 7. If the two dice show 1 and 1, then the running total should be 2 plus
the total of another throw. Rolls stop when the dice rolls are different.

In [23]:
import random

In [30]:
def my_monopoly_dice():
    sum = 0
    x = random.randint(1,6)
    y = random.randint(1,6)
    while x == y:
        sum = x + y 
        y = random.randint(1,6)
    else:
        sum = sum + x + y
    return sum

In [31]:
my_monopoly_dice()

9

In [38]:
my_monopoly_dice()

20

9. A number is prime if it is divisible without remainder only by itself and 1. The number 1 is not
a prime. Write a function my_is_prime(n) where the output is 1 if n is prime and 0 is otherwise.
Assume that n is a strictly positive integer.

In [39]:
import math as m

In [46]:
def my_is_prime(n):
    flag = 0
    for i in range(2, int(m.sqrt(n))+1):
        if n%2==0:
            flag = 1
            break
    return flag

In [52]:
my_is_prime(8)

1

In [53]:
my_is_prime(2)

0

10. Write a function my_n_primes(n) where prime is a list of the first n primes. Assume that n is a
strictly positive integer.

In [54]:
def my_n_primes(n):
    primes = []
    num = 2
    while len(primes) < n:
        is_prime = True
        for p in primes:
            if p * p > num:
                break
            if num % p == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
        num += 1
    return primes

In [55]:
my_n_primes(10)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

11. Write a function my_n_fib_primes(n) where the output fib_primes is a list of the first n numbers
that are both a Fibonacci number and a prime. Note that 1 is not prime. Hint: Do not use the
recursive implementation of Fibonacci numbers. A function to compute Fibonacci numbers is
presented in Section 6.1. You may use the code freely.

In [56]:
def my_n_fib_primes(n):
    fib_primes = []
    fibs = [0, 1]
    while len(fib_primes) < n:
        next_fib = fibs[-1] + fibs[-2]
        fibs.append(next_fib)
        if next_fib > 1:
            is_prime = True
            for i in range(2, int(next_fib**0.5) + 1):
                if next_fib % i == 0:
                    is_prime = False
                    break
            if is_prime:
                fib_primes.append(next_fib)
    return fib_primes


In [57]:
my_n_fib_primes(6)

[2, 3, 5, 13, 89, 233]

12. Write a function my_trig_odd_even(M) where the output Q[i,j] = sin(π/M[i,j]) if M[i,j] is
odd, and Q[i,j] = cos(π/M[i,j]) if M[i,j] is even. Assume that M is a two-dimensional array
of strictly positive integers.

In [58]:
import numpy as np

def my_trig_odd_even(M):
    M = np.array(M)
    Q = np.zeros_like(M, dtype=float)
    
    odd_indices = M % 2 == 1
    even_indices = M % 2 == 0

    Q[odd_indices] = np.sin(np.pi / M[odd_indices])
    Q[even_indices] = np.cos(np.pi / M[even_indices])

    return Q

In [60]:
print(my_trig_odd_even(np.array([[2,5,4],[3,5,4]])))

[[6.12323400e-17 5.87785252e-01 7.07106781e-01]
 [8.66025404e-01 5.87785252e-01 7.07106781e-01]]


13. Let C be a square connectivity array containing zeros and ones. Point i has a connection to point
j or i is connected to j if C[i,j] = 1. Note that connections in this context are one-directional,
meaning C[i,j] is not necessarily the same as C[j,i]. For example, think of a one-way street
from point A to point B. If A is connected to B, then B is not necessarily connected to A.
Write a function my_connectivity_mat_2_dict(C, names) where C is a connectivity array and
names is a list of strings that denote the name of a point. That is, names[i] is the name of the name
of the ith point.
The output variable node should be a dictionary with the key as the string in names, and value is
a vector containing the indices j, such that C[i,j] = 1. In other words, it is a list of points that
point i is connected to.

In [68]:
def my_connectivity_mat_2_dict(C, names):
    node = {}
    for i, name in enumerate(names):
        node[name] = [j + 1 for j in range(len(C[i])) if C[i][j] == 1]
    return node

In [69]:
C = [[0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1], [1, 1, 1, 0]]
names = ["Los Angeles", "New York", "Miami", "Dallas"]
print(my_connectivity_mat_2_dict(C,names))

{'Los Angeles': [2, 4], 'New York': [1, 4], 'Miami': [4], 'Dallas': [1, 2, 3]}


14. Turn the list words of lower case characters to upper case using the list comprehension.

In [70]:
list = ["hi","hello","world"]
L = [i.upper() for i in list]
print(L)

['HI', 'HELLO', 'WORLD']
