# Chapter 2 exercise solutions

1. Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.

In [1]:
x = 2
y = 3
del x


2. Write a line of code that generates the following error:
NameError: name "x" is not defined

In [2]:
print(x)

NameError: name 'x' is not defined

3. Let x = 10 and y=3. Write a line of code that will make each of the following assignments.
u=x+y, 
v = xy, 
w = x/y, 
z = sin(x), 
r = 8sin(x), 
s = 5sin(xy), 
p=x**y

In [3]:
import math as m

In [4]:
x = 10 
y=3
u=x+y
v = x*y
w = x/y
z = m.sin(x)
r = 8*m.sin(x)
s = 5*m.sin(x*y)
p=x**y

4. Show all the variables in the Jupyter notebook after you finish Problem 3

In [5]:
%whos

Variable   Type      Data/Info
------------------------------
m          module    <module 'math' (built-in)>
p          int       1000
r          float     -4.352168887114958
s          float     -4.940158120464309
u          int       13
v          int       30
w          float     3.3333333333333335
x          int       10
y          int       3
z          float     -0.5440211108893698


5. Assign string "123" to the variable S. Convert the string into a float type and assign the output to
the variable N. Verify that S is a string and N is a float using the type function.

In [6]:
s = "123"
N = float(s)
print(type(s))
print(type(N))

<class 'str'>
<class 'float'>


6. Assign the string "HELLO" to the variable s1 and the string "hello" to the variable s2. Use the ==
operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the
lower method is used on s1. Use the == operator to show that s1 and s2 are equal if upper method
is used on s2.

In [4]:
s1 = "HELLO"
s2 = "hello"
a = (s1==s2)
print("is s1==s2? ",a)
b = (s1.lower()==s2)
print("is s1.lower()==s2? ",b)
c = (s1==s2.upper())
print("is s1==s2.lower()? ",c)

is s1==s2?  False
is s1.lower()==s2?  True
is s1==s2.lower()?  True


7. Use the print function to generate the following strings:
• The word "Engineering" has 11 letters.
• The word "Book" has 4 letters.

In [5]:
print("The word \"Engineering\" has 11 letters.")
print("The word \"Book\" has 4 letters.")

The word "Engineering" has 11 letters.
The word "Book" has 4 letters.


8. Check if "Python" is in "Python is great!".

In [6]:
if "Python" in "Python is great":
    print(True)
else:
    print(False)

True


9. Get the last word "great" from "Python is great!"

In [8]:
str = "Python is great!"
print(str[10:15])

great


10. Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method.
Append 4 to the list_a using the append method.

In [9]:
list_a = [1,8,9,15]
list_a.insert(1,2)
list_a.append(4)

In [10]:
print(list_a)

[1, 2, 8, 9, 15, 4]


11. Sort the list_a in problem 10 in ascending order

In [11]:
list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


12. Turn "Python is great!" into a list

In [12]:
print(list("Python is great!"))

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'g', 'r', 'e', 'a', 't', '!']


13. Create one tuple with element "One", 1 and assign it to tuple_a.

In [13]:
tuple_a = ("One", 1)

14. Get the second element in the tuple_a in Problem 13

In [14]:
print(tuple_a[1])

1


15. Get the unique element from (2, 3, 2, 3, 1, 2, 5)

In [15]:
s = set((2,3,2,3,1,2,5))
print(s)

{1, 2, 3, 5}


16. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Obtain the following:
• union of set_a and set_b
• intersection of set_a and set_b
• difference of set_a to set_b using difference method

In [17]:
set_a = {2,3,2}
set_b = {1,2,3}
print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


17. Create a dictionary that has the keys "A", "B", "C" with values "a", "b", "c" individually. Print all
the keys in the dictionary.

In [18]:
d = {"A":"a", "B":"b", "C":"c"}
print(d.keys())

dict_keys(['A', 'B', 'C'])


18. Check if key "B" is in the dictionary defined in Problem 17.

In [19]:
if "B" in d:
    print(True)
else:
    print(False)

True


19. Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the
assignments from Problem 3.

In [27]:
import numpy as np

In [28]:
x = np.array([1,4,3,2,9,4])
y = np.array([2,3,4,1,2,3])
print(x + y)
print(x*y)
print(x/y)
print(np.sin(x))
print(8*np.sin(x))
print(5*np.sin(x*y))
print(x**y)

[ 3  7  7  3 11  7]
[ 2 12 12  2 18 12]
[0.5        1.33333333 0.75       2.         4.5        1.33333333]
[ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ]
[ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996]
[ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459]
[ 1 64 81  2 81 64]


20. Generate an array with size 100 evenly spaced between −10 to 10 using linspace function in
NumPy.

In [29]:
x = np.linspace(-10,10,100)
print(x)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

21. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the
index of the array.

In [31]:
array_a = np.array([-1,0,1,2,0,3])
x = array_a[array_a>0]
print(x)

[1 2 3]


22. Create an array y =$
\begin{bmatrix}
3 & 5 & 3 \\
2 & 2 & 5 \\
3 & 8 & 9
\end{bmatrix}
$
and calculate its transpose.

In [30]:
y = np.array([[3,5,3],[2,2,5],[3,8,9]])
print(y.T)

[[3 2 3]
 [5 2 8]
 [3 5 9]]


23. Create a 2 × 4 zero array

In [33]:
k = np.zeros((2,4))
print(k)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


24. Change the second column in the above array to 1

In [34]:
k[:,1]=1
print(k)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


25. Write a magic command to clear all the variables in the Jupyter notebook.

%reset


(I havn't written in this code mode since I dont want to delete all variables from the namespace)