# Chapter 4 exercise solutions

1. Write a function my_tip_calc(bill, party) where bill is the total cost of a meal and party is
the number of people in the group. The tip should be calculated as 15% for a party strictly less than
six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party
11 or more.

In [1]:
def my_tip_calc(bill, party):
    if party < 6:
        tip_percentage = 0.15
    elif party < 8:
        tip_percentage = 0.18
    elif party < 11:
        tip_percentage = 0.20
    else:
        tip_percentage = 0.25
    
    tip = bill * tip_percentage
    return tip


In [2]:
t = my_tip_calc(109.29,3)
print(t)

16.3935


2. Write a function my_mult_operation(a,b,operation). The input argument, operation, is a string
that is either "plus", "minus", "mult", "div", or "pow", and the function should compute: a + b,
a − b, a ∗ b, a/b, and a^b for the respective values for operation. 

In [10]:
def my_mult_operation(a, b, operation):
    if operation == "plus":
        return a + b
    elif operation == "minus":
        return a - b
    elif operation == "mult":
        return a * b
    elif operation == "div":
        try:
            return a / b
        except:
            print("division by zero not allowed")
    elif operation == "pow":
        return a ** b
    else:
        return "Error: Invalid operation"


In [4]:
import numpy as np

In [5]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])


In [6]:
my_mult_operation(x,y,"plus")

array([3, 5, 7, 9])

In [7]:
my_mult_operation(x,y,"minus")

array([-1, -1, -1, -1])

In [8]:
my_mult_operation(x,y,"mult")

array([ 2,  6, 12, 20])

In [11]:
my_mult_operation(x,y,"div")

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [12]:
my_mult_operation(x,y,"pow")

array([   1,    8,   81, 1024])

3. Consider a triangle with vertices at (0, 0), (1, 0), and (0, 1). Write a function with the name
my_inside_triangle(x,y) where the output is the string "outside" if the point (x, y) is outside
of the triangle, "border" if the point is exactly on the border of the triangle, and "inside" if the
point is on the inside of the triangle.

In [13]:
def my_inside_triangle(x, y):
    def area(x1, y1, x2, y2, x3, y3):
        return abs((x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2)) / 2.0)
    
    A = area(0, 0, 1, 0, 0, 1)
    A1 = area(x, y, 1, 0, 0, 1)
    A2 = area(0, 0, x, y, 0, 1)
    A3 = area(0, 0, 1, 0, x, y)
    
    if A1 + A2 + A3 > A:
        return "outside"
    elif A1 == 0 or A2 == 0 or A3 == 0:
        return "border"
    else:
        return "inside"


In [14]:
my_inside_triangle(.5,.5)

'border'

In [15]:
my_inside_triangle(.25,.25)

'inside'

In [16]:
my_inside_triangle(5,5)

'outside'

4. Write a function my_make_size10(x) where x is an array, and output is the first 10 elements of x if
x has more than 10 elements, and output is the array x padded with enough zeros to make it length
10 if x has less than 10 elements.

In [17]:
import numpy as np

def my_make_size10(x):
    if len(x) > 10:
        return x[:10]
    else:
        return np.pad(x, (0, 10 - len(x)), 'constant')


In [18]:
my_make_size10(range(1,2))

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
my_make_size10(range(1,15))

range(1, 11)

5. Can you write my_make_size10 without using if-statements (i.e., using only logical and array operations)?

In [21]:
import numpy as np

def my_make_size10(x):
    return np.pad(x, (0, max(0, 10 - len(x))), 'constant')[:10]


In [22]:
print(my_make_size10(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])))  
print(my_make_size10(np.array([1, 2, 3])))                               


[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 0 0 0 0 0 0 0]


6. Write a function my_letter_grader(percent) where the grade is the string "A+" if percent is
greater than 97, "A" if percent is greater than 93, "A-" if percent is greater than 90, "B+" if
percent is greater than 87, "B" if percent is greater than 83, "B-" if percent is greater than 80,
"C+" if percent is greater than 77, "C" if percent is greater than 73, "C-" if percent is greater than
70, "D+" if percent is greater than 67, "D" if percent is greater than 63, "D-" if percent is greater
than 60, and "F" for any percent less than 60. Grades exactly on the division should be included in
the higher grade category.

In [23]:
def my_letter_grader(percent):
    grades = ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F"]
    thresholds = [97, 93, 90, 87, 83, 80, 77, 73, 70, 67, 63, 60, -float("inf")]
    for i in range(len(thresholds)):
        if percent >= thresholds[i]:
            return grades[i]


In [24]:
my_letter_grader(97)

'A+'

In [25]:
my_letter_grader(84)

'B'

7. Most engineering systems have a built-in redundancy. That is, an engineering system has fail-safes
incorporated into the design to accomplish its purpose. Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree.
Write a function my_nuke_alarm(s1,s2,s3) where s1, s2, and s3 are the temperature readings for
sensor 1, sensor 2, and sensor 3, respectively. The output should be the string "alarm!" if any two
of the temperature readings disagree by strictly more than 10 degrees and "normal" otherwise.

In [26]:
def my_nuke_alarm(s1, s2, s3):
    if abs(s1 - s2) > 10 or abs(s1 - s3) > 10 or abs(s2 - s3) > 10:
        return "alarm!"
    else:
        return "normal"


In [27]:
my_nuke_alarm(94,96,90)

'normal'

In [28]:
my_nuke_alarm(94,96,80)

'alarm!'



8. Let \( Q(x) \) be a quadratic equation defined as:
\[ Q(x) = ax^2 + bx + c \]
where \( a \), \( b \), and \( c \) are scalar coefficients. The roots of \( Q(x) \) are solutions to:
\[ Q(r) = 0 \]

The quadratic formula to find the roots is:
\[ r = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a} \]

Depending on the value of the discriminant (\( \Delta = b^2 - 4ac \)), the nature of the roots is:
- Two real roots: If \( \Delta > 0 \)
- One real root: If \( \Delta = 0 \)
- Two imaginary roots: If \( \Delta < 0 \)




In [29]:
import numpy as np

def my_n_roots(a, b, c):
    discriminant = b**2 - 4*a*c
    if discriminant > 0:
        n_roots = 2
        r = [(-b + np.sqrt(discriminant)) / (2 * a), (-b - np.sqrt(discriminant)) / (2 * a)]
    elif discriminant == 0:
        n_roots = 1
        r = [-b / (2 * a)]
    else:
        n_roots = -2
        real_part = -b / (2 * a)
        imag_part = np.sqrt(-discriminant) / (2 * a)
        r = [complex(real_part, imag_part), complex(real_part, -imag_part)]
    return n_roots, r

In [30]:
n_roots, r = my_n_roots(1,0,-9)
print(n_roots, r)

2 [np.float64(3.0), np.float64(-3.0)]


In [31]:
my_n_roots(3,4,5)

(-2,
 [(-0.6666666666666666+1.1055415967851332j),
  (-0.6666666666666666-1.1055415967851332j)])

In [32]:
my_n_roots(2,4,2)

(1, [-1.0])

9. Write a function my_split_function(f,g,a,b,x), where f and g are function objects f(x) and
g(x), respectively. The output should be f(x) if x ≤ a, g(x) if x ≥ b, and 0 otherwise. Assume
that b>a.

In [33]:
def my_split_function(f, g, a, b, x):
    if x <= a:
        return f(x)
    elif x >= b:
        return g(x)
    else:
        return 0


In [34]:
def f(x):
    return x**2

def g(x):
    return x + 10

# Test the function
print(my_split_function(f, g, 5, 10, 3))  
print(my_split_function(f, g, 5, 10, 8))  
print(my_split_function(f, g, 5, 10, 12)) 


9
0
22
